app/routes/game.py
import json
from flask import Blueprint, render_template, request, current_app
from app import database
from app import shared

game_page = Blueprint("game", __name__, template_folder="templates")

@game_page.route('/pvai')
def create_vs_ai():
    grid_data = [[(y, [(x, "") for x in range(10)]) for y in range(10)],
                 [(y, [(x, "") for x in range(10)]) for y in range(10)]]
    return render_template("game.html", p1_ready=False, p2_ready=True, turn=0,
                           status="setup", grid_data=grid_data, game_type="pvai")

@game_page.route('/<lobby_id>', methods=['GET'])
def join_game(lobby_id):
    if lobby_id == "test123":
        grid_data = [[(y, [(x, "") for x in range(10)]) for y in range(10)],
                     [(y, [(x, "") for x in range(10)]) for y in range(10)]]
        grid_data[0][2][1][0] = (0, "placed-ship ship-submarine")
        grid_data[0][3][1][0] = (0, "placed-ship ship-submarine")
        grid_data[0][4][1][0] = (0, "placed-ship ship-submarine")
        grid_data[0][2][1][1] = (1, "placed-ship ship-battleship")
        grid_data[0][3][1][1] = (1, "placed-ship ship-battleship")
        grid_data[0][4][1][1] = (1, "placed-ship ship-battleship")
        grid_data[0][6][1][3] = (3, "placed-ship ship-aircraft")
        grid_data[0][6][1][4] = (4, "placed-ship ship-aircraft")
        grid_data[0][6][1][5] = (5, "placed-ship ship-aircraft")
        grid_data[0][6][1][6] = (6, "placed-ship ship-aircraft")
        grid_data[0][2][1][3] = (3, "placed-ship ship-cruiser")
        grid_data[0][3][1][3] = (3, "placed-ship ship-cruiser")
        grid_data[0][2][1][4] = (4, "placed-ship ship-patrol")
        grid_data[0][3][1][4] = (4, "placed-ship ship-patrol")
        return render_template("game.html", p1_ready=True, p2_ready=True,
                               turn=1, status="underway",
                               grid_data=grid_data, game_type="pvai")

    lobby_data = database.get_lobby_data(lobby_id)

    if lobby_data[0] is not None:
        if not shared.verify_user_cookie():
            return shared.invalid_user()

        grid_data = [[(y, [(x, "") for x in range(10)]) for y in range(10)],
                     [(y, [(x, "") for x in range(10)]) for y in range(10)]]
        shots_self = [[False for x in range(10)] for y in range(10)]
        shots_opp = [[False for x in range(10)] for y in range(10)]
        game_data = database.get_game_data(lobby_id)
        cookie_data = json.loads(request.cookies["battleship"])
        ship_data, shot_data = database.get_grid_data(lobby_data[0][0], None)

        owner = cookie_data["owner"]

        for shot_x, shot_y, shot_owner in shot_data:
            player = 1 if shot_owner == owner else 0
            if player == 1:
                shots_self[shot_y][shot_x] = True
            else:
                shots_opp[shot_y][shot_x] = True
            val = "shot-missed"
            grid_data[player][shot_y][1][shot_x] = (shot_x, val)

        for ship_x, ship_y, ship_owner, ship_id, sunk in ship_data:
            ship_id = "ship-" + ship_id.split("_")[1]
            shot_at_opp = shots_self[ship_y][ship_x]
            shot_at_self = shots_opp[ship_y][ship_x]
            if ship_owner == owner:
                if sunk:
                    grid_data[0][ship_y][1][ship_x] = (ship_x, "sunk-ship " + ship_id)
                elif shot_at_self:
                    grid_data[0][ship_y][1][ship_x] = (ship_x, "hit-ship " + ship_id)
                else:
                    grid_data[0][ship_y][1][ship_x] = (ship_x, "placed-ship " + ship_id)
            else:
                show_ship = " " + ship_id if lobby_data[0][2] == "ended" else ""
                if sunk:
                    grid_data[1][ship_y][1][ship_x] = (ship_x, "sunk-ship" + show_ship)
                elif shot_at_opp:
                    grid_data[1][ship_y][1][ship_x] = (ship_x, "hit-ship" + show_ship)
                elif lobby_data[0][2] == "ended": # If game is over, we show the enemy board.
                    grid_data[1][ship_y][1][ship_x] = (ship_x, "placed-ship" + show_ship)

        self_ready = game_data[2 - owner] == 1
        other_ready = game_data[owner+1] == 1
        player_turn = game_data[5] == owner

        return render_template("game.html", p1_ready=self_ready, p2_ready=other_ready,
                               turn=player_turn, status=lobby_data[0][2],
                               grid_data=grid_data, game_type="pvp")
    return shared.invalid_lobby()

app/routes/index.py
from flask import Blueprint, render_template

start_page = Blueprint("index", __name__, template_folder="templates")

@start_page.route('/')
@start_page.route('/index')
def index():
    return render_template("index.html")

app/routes/lobby.py
import flask
from app import database
from app import shared

lobby_page = flask.Blueprint("lobby", __name__, template_folder="templates")

@lobby_page.route("/pvp/new")
def new_pvp():
    resp = flask.make_response(flask.render_template("lobby.html"))
    resp.set_cookie("battleship", "", expires=0)
    return resp

@lobby_page.route('/pvp')
def lobby_pvp():
    return flask.render_template("lobby.html")

@lobby_page.route("/pvai/")
def new_pvai():
    return flask.redirect(flask.url_for("game.create_vs_ai"))

@lobby_page.route("/pvp/<lobby_id>", methods=['GET'])
def join_new_lobby(lobby_id):
    resp = flask.make_response(join_lobby("pvp", lobby_id))
    resp.set_cookie("battleship", "", expires=0)
    return resp

@lobby_page.route('/<lobby_type>/<lobby_id>', methods=['GET'])
def join_lobby(lobby_type, lobby_id):
    if lobby_type not in ("pvp", "pvai"):
        return flask.Response("Page not found.", status=404, mimetype='text/html')
    lobby_data = database.get_lobby_data(lobby_id)
    if lobby_data[0] is None:
        return shared.invalid_lobby()
    if lobby_data[0][2] != "pending":
        return shared.error_response("Lobby is full.", 403)
    return flask.render_template("lobby.html", lobby_id=lobby_id)

app/routes/search.py
import json
from flask import Blueprint, render_template, request
from app import database
from app import shared

search_page = Blueprint("search", __name__, template_folder="templates")

@search_page.route('/')
def search_game():
    lobbies = database.get_public_lobbies()
    active_lobby = None
    if shared.verify_user_cookie():
        cookie_data = json.loads(request.cookies["battleship"])
        active_lobby = cookie_data["id"]
    return render_template("search.html", lobbies=lobbies, active_lobby=active_lobby)

app/templates/base.html
<html>
<head>
    {% block head %}
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/shared.css') }}">
    {% endblock %}
</head>
<body>
    <div class="wrapper">
        <a id="logo-link" href="/projects/battleship">
            <h1>Battleship</h1>
        </a>
        <div class="inner">
            {% block content %}{% endblock %}
        </div>
    </div>
{% block scripts %}{% endblock %}
</body>
</html>

app/templates/chat.html
<div id="chat-wrapper">
    <div id="chat-inner">
        <div id="chat-content"></div>
        <div id="chat-write">
            <input id="chat-input">
            <button id="chat-send">Send</button>
        </div>
    </div>
</div>

<p class="chat-msg template-msg">
    <span class="chat-msg-author"></span><span class="chat-msg-content"></span>
</p>

app/templates/error.html
{% import "return_button.html" as return_btn %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/shared.css') }}">
    </head>
    <body>
        <div id="error-div">
            <h1>Error!</h1>
            <h2>{{ error_msg }}</h2>
            {{ return_btn.button('Return') }}
        </div>
    </body>
</html>

app/templates/game.html
{% extends "base.html" %}
{% block title %}Battleship{% endblock %}
{% block head %}
{{ super() }}
<script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js" integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf-8">
    var socket = io();
</script>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/game.css') }}">
{% endblock %}
{% block content %}
{% import "return_button.html" as return_btn %}
<div id="game-div">
    <div class="{% if p1_ready or status == 'underway' %}hidden{% else %}game-ships{% endif %}">
        <button class="ship-btn" data-ship_size="2" data-ship_id="ship-patrol">
            <img src="{{ url_for('static', filename='img/ship-patrol_horizontal.png') }}">
        </button>
        <button class="ship-btn" data-ship_size="2" data-ship_id="ship-cruiser">
            <img src="{{ url_for('static', filename='img/ship-cruiser_horizontal.png') }}">
        </button>
        <button class="ship-btn" data-ship_size="3" data-ship_id="ship-battleship">
            <img src="{{ url_for('static', filename='img/ship-battleship_horizontal.png') }}">
        </button>
        <button class="ship-btn" data-ship_size="3" data-ship_id="ship-submarine">
            <img src="{{ url_for('static', filename='img/ship-submarine_horizontal.png') }}">
        </button>
        <button class="ship-btn" data-ship_size="4" data-ship_id="ship-aircraft">
            <img src="{{ url_for('static', filename='img/ship-aircraft_horizontal.png') }}">
        </button>
    </div>
    <div id="game-boards-wrapper">
        <div id="game-own-board" class="game-board {% if status != 'setup' %}board-disabled{% endif %}">
            {% for y, row in grid_data[0] %}
                <div class="grid-row {% if loop.first %}row-first{% elif loop.last %}row-last{% endif %}">
                {% for x, grid in row %}
                    <button class="grid-button-self {{ grid }}" data-x="{{ x }}" data-y="{{ y }}">
                        
                    </button>
                {% endfor %}
                </div>
            {% endfor %}
            {% if status == 'setup' %}
                <p id="status-self" class="player-{% if p1_ready %}ready{% else %}waiting{% endif %}">
                    {% if not p1_ready %}Not{% endif %} Ready
                </p>
            {% elif status == 'ended' %}
                <p id="status-self" class="player-{% if not turn %}ready{% else %}waiting{% endif %}">
                    {% if not turn %}Winner!{% else %}Loser!{% endif %}
                </p>
            {% else %}
                <p id="status-self" class="player-hide">
                    Fire at Will!
                </p>
            {% endif %}
        </div>
        <div id="game-enemy-board" class="game-board {% if status in ('setup', 'ended') or not turn %}board-disabled{% endif %}">
            {% for y, row in grid_data[1] %}
                <div class="grid-row {% if loop.first %}row-first{% elif loop.last %}row-last{% endif %}">
                {% for x, grid in row %}
                    <button class="grid-button-opp {{ grid }}" data-x="{{ x }}" data-y="{{ y }}">
                        
                    </button>
                {% endfor %}
                </div>
            {% endfor %}
            {% if status == 'setup' %}
                <p id="status-opponent" class="player-{% if p2_ready %}ready{% else %}waiting{% endif %}">
                    {% if not p2_ready %}Not{% endif %} Ready
                </p>
            {% else %}
                <p id="status-opponent" class="player-{% if status == 'underway' %}turn{% elif turn %}ready{% else %}waiting{% endif %}">
                    {% if status == 'ended' %}
                        {% if turn %}Winner!{% else %}Loser!{% endif %}
                    {% elif turn %}
                        Fire at Will!
                    {% else %} 
                        Waiting for Move
                    {% endif %}
                </p>
            {% endif %}
        </div>
    </div>
    {% if status == 'ended' %}
        {{ return_btn.button('Exit') }}
    {% else %}
    <button id="player-action-btn" {% if not turn or status == 'setup' %}disabled="disabled"{% endif %}
            onclick="{% if status == 'setup' %}markAsReady();{% elif status == 'underway' %}makeMove();{% endif %}">
        {% if status == 'setup' %}Ready{% else %}Fire!{% endif %}
    </button>
    {% endif %}
</div>

{% include "chat.html" %}

{% endblock %}

{% block scripts %}
<canvas id="canvas"></canvas>
<div id="game-over-modal">
    <h1 id="game-over-header-won">Victory!</h1>
    <h1 id="game-over-header-lost">Defeat!</h1>
    <div id="game-over-splash">
        <img id="splash-won" src="{{ url_for('static', filename='img/victory.jpg') }}">
        <img id="splash-lost" src="{{ url_for('static', filename='img/defeat.jpg') }}">
        <button onclick="closeGameOverModal();">Close</button>
    </div>
</div>

<script type="text/javascript" src="{{ url_for('static', filename='js/chat.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/shared.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/canvashelper.js') }} "></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/animate.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/game.js') }}"></script>
{% if game_type == 'pvp' %}
<script>
    socket.emit("player_joined", getCookieVal("battleship"));
</script>
{% else %}
<script type="text/javascript" src="{{ url_for('static', filename='js/ai.js') }}"></script>
<script>
    socket.emit("ai_init", "whew");
</script>
{% endif %}
{% if status == 'setup' %}
    <script>initSetup();</script>
{% else %}
    <script>initGame();</script>
{% endif %}
{% endblock %}

app/templates/game_over.html
{% import "return_button.html" as return_btn %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/shared.css') }}">
    </head>
    <body>
        <div id="error-div">
            <h1>This game has concluded.</h1>
            {{ return_btn.button('Return') }}
        </div>
    </body>
</html>

app/templates/index.html
<html>
<head>
    <title>Battleship</title>
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/shared.css') }}">
</head>
<body>
    <div class="wrapper">
        <img id="main-title" width="1000px" src="{{ url_for('static', filename='img/main-title.png') }}">
        <div id="main-menu">
            <button onclick="showGameType();">Create game</button>
            <a href="{{ url_for('search.search_game') }}">
                <button>Find game</button>
            </a>
            <div id="game-type">
                <a href="{{ url_for('lobby.new_pvp') }}">
                    <button>VS. Player</button>
                </a>
                <a href="{{ url_for('lobby.new_pvai')}}">
                    <button>VS. AI</button>
                </a>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>
</html>

app/templates/lobby.html
{% extends "base.html" %}
{% block title %}Lobby{% endblock %}
{% block head %}
{{ super() }}
<script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js" integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf-8">
    var socket = io();
</script>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/lobby.css') }}">
{% endblock %}
{% block content %}
<h1>Lobby</h1>
<div id="lobby-config">
    <div class="lobby-option">Name: <input id="lobby-name" value="Battleship Lobby" disabled onchange="lobbyNameChanged();"></div>
    <div class="lobby-option">Lobby ID: <span id="lobby-id">{{ lobby_id }}</span></div>
    <div class="lobby-option">Invite Only: <input id="invite-only" type="checkbox" checked disabled onchange="checkPublicChanged();"></div>
    <div class="lobby-option">
        Lobby URL: <input id="lobby-url" type="text" readonly value="{{ url_for('lobby.join_lobby', lobby_type='pvp', lobby_id=lobby_id) }}">
        <button id="copy-lobby-url" onclick="copyURL();">Copy</button>
    </div>
</div>

<button id="start-lobby-btn" onclick="startSetup();" disabled>Start</button>

{% include "chat.html" %}
{% endblock %}
{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='js/chat.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/shared.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/lobby.js') }}"></script>
{% endblock %}

app/templates/return_button.html
{% macro button(text) -%}
    <button onclick="window.location.href='http://mhooge.com:5000/projects/battleship'">{{ text }}</button>
{%- endmacro %}

app/templates/search.html
{% extends "base.html" %}
{% block title %}Battleship{% endblock %}
{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/search.css') }}">
{% endblock %}
{% block content %}
<h1>Public Lobbies</h1>
<button id="refresh-list-btn" onclick="window.location.reload();">
    <img src="{{ url_for('static', filename='img/repeat.png') }}">
</button>
<div id="lobbies-list">
    {% if not lobbies %}
        <div id="no-lobbies">There are no public & active lobbies.</div>
    {% else %}
        <div class="lobby-list-elem list-header">
            <div class="lobby-name">Name</div>
            <div class="lobby-id">Lobby ID</div>
            <div class="lobby-status">Status</div>
            <div class="header-padding">dasd</div>
        </div>
        {% for id, name, status in lobbies %}
            <div class="lobby-list-elem">
                <div class="lobby-name">{{ name }}</div>
                <div class="lobby-id">{{ id }}</div>
                <div class="lobby-status status-{{status}}">{{ status }}</div>
                {% if (status != 'ended' and id == active_lobby) or status == 'pending' %}
                    <a href="{% if id == active_lobby %}{{ url_for('game.join_game', lobby_id=id) }}
                            {% else %}{{ url_for('lobby.join_new_lobby', lobby_id=id) }}{% endif %}">
                        <button class="join-button">
                            {% if id == active_lobby %}Rejoin{% else %}Join{% endif %}
                        </button>
                    </a>
                {% else %}
                    <div class="cant-join"></div>
                {% endif %}
            </div>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}